name: shop_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.0-218.1.beta <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  http: ^0.13.6
  shared_preferences: ^2.1.2
  equatable: ^2.0.5
  internet_connection_checker: ^1.0.0+1
  file_picker: ^5.3.1
  image_picker: ^0.8.9
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  cloudinary_public: ^0.21.0
  intl: ^0.18.1
  syncfusion_flutter_charts: ^22.2.12
  flutter_charts: ^0.5.1
  dotted_border: ^2.0.0+3
  intl_phone_field: ^3.2.0
  country_picker: ^2.0.20
  timer_count_down: ^2.2.2
  quiver: ^3.2.1
  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.4
  flutter_local_notifications: ^15.0.1
  shimmer: ^2.0.0
  get_storage: ^2.1.1
  socket_io_client: ^2.0.2
  flutter_paypal_checkout: ^1.0.1
  i18n_extension: ^9.0.2
  phosphor_flutter: ^1.3.1
  just_audio: ^0.9.34
  fluttertoast: ^8.2.2
  flutter_stripe: ^9.4.0
  device_info_plus: ^9.0.3
  motion_toast: ^2.7.8
  flutter_blurhash: ^0.8.2
  dio: ^5.3.2
  lottie: ^2.6.0
  font_awesome_flutter: ^10.5.0
  flutter_slidable: ^0.6.0
  google_maps_flutter: ^2.3.0
  geolocator: ^9.0.0
  geocoding: ^2.0.5
  google_api_headers: ^2.0.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  # flutter_geofire: ^2.0.3
  flutter_polyline_points: ^1.0.0
  location: ^5.0.3
  flutter_localizations:
    sdk: flutter
  

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo_foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lotties/
    - assets/languages/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf

    - family: Allison
      fonts:
        - asset: assets/fonts/Allison-Regular.ttf

    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript.ttf
